obj-$(CONFIG_CSI_VFE)           += cci.o

obj-m			+= ov5640.o
obj-m			+= s5k4ec.o
obj-m			+= s5k4ec_mipi.o
obj-m			+= gc2035.o
obj-m			+= gt2005.o
obj-m			+= gc0307.o
obj-m			+= gc0308.o
obj-m			+= gc0329.o
obj-m			+= hi253.o

obj-m			+= ov5650.o
obj-m			+= ov5647.o
obj-m			+= t8et5.o
obj-m			+= s5k4e1.o
obj-m			+= s5k4e1_mipi.o
obj-m			+= sp2518.o
obj-m			+= sp0718.o



